CREATE TABLE CUSTOMER
(
    ID          SERIAL,
    FIRST_NAME  VARCHAR(255),
    LAST_NAME   VARCHAR(255),
    EMAIL       VARCHAR(255),
    PESEL       VARCHAR(255),
    TYPE        VARCHAR(255), -- INDIVIDUAL / BUSINESS
    STATUS      VARCHAR(255), -- ACTIVE / NOT_ACTIVE
    CREATE_DATE TIMESTAMP(255),
    MODIFY_DATE TIMESTAMP(255),
    PRIMARY KEY (ID)
);

CREATE TABLE SERVICE
(
    ID           SERIAL,
    CUSTOMER_ID  INTEGER,
    TYPE         VARCHAR(255), -- TV / SERVICE / INTERNET
    SERVICE_NAME VARCHAR(255),
    SIM          VARCHAR(255),
    SIM_TYPE     VARCHAR(255), -- ESIM / SIM
    SIM_NUMBER   VARCHAR(255),
    STATUS       VARCHAR(255), -- ACTIVE / NOT_ACTIVE
    CREATE_DATE  TIMESTAMP(255),
    MODIFY_DATE  TIMESTAMP(255),
    PRIMARY KEY (ID)
);

CREATE TABLE COMPONENT
(
    ID              SERIAL,
    SERVICE_ID      INTEGER,
    NAME            VARCHAR(255),
    EXPIRY_DATE     TIMESTAMP NOT NULL,
    TYPE            VARCHAR(255),
    PARAMETER_NAME  VARCHAR(255),
    PARAMETER_VALUE VARCHAR(255),
    STATUS          VARCHAR(255), -- ACTIVE / NOT_ACTIVE
    CREATE_DATE     TIMESTAMP(255),
    MODIFY_DATE     TIMESTAMP(255),
    PRIMARY KEY (ID)
);

CREATE TABLE INVOICE
(
    ID                        SERIAL,
    CUSTOMER_ID               INTEGER,
    BILLING_PERIOD_START_DATE TIMESTAMP,
    BILLING_PERIOD_END_DATE   TIMESTAMP,
    PRICE_GROSS               VARCHAR(255),
    STATUS                    VARCHAR(255), -- PAID / UNPAID
    CREATE_DATE               TIMESTAMP(255),
    MODIFY_DATE               TIMESTAMP(255),
    PRIMARY KEY (ID)
);

CREATE TABLE COMPONENT_CATALOG
(
    ID              SERIAL,
    TYPE            VARCHAR(255),
    PRICE_MIN       VARCHAR(255),
    PRICE_MAX       VARCHAR(255),
    PARAMETER_NAME  VARCHAR(255),
    PARAMETER_VALUE VARCHAR(255),
    STATUS          VARCHAR(255), -- ACTIVE / NOT_ACTIVE
    CREATE_DATE     TIMESTAMP(255),
    MODIFY_DATE     TIMESTAMP(255),
    PRIMARY KEY (ID)
);

CREATE TABLE ORDER
(
    ID          SERIAL,
    CUSTOMER_ID INTEGER,
    STATUS      VARCHAR(255), -- NEW / PROCESSING / CLOSED / ERROR
    CREATE_DATE TIMESTAMP(255),
    MODIFY_DATE TIMESTAMP(255),
    PRIMARY KEY (ID)
);

CREATE TABLE ORDER_ITEM
(
    ID                   SERIAL,
    ORDER_ID             INTEGER,
    COMPONENT_CATALOG_ID INTEGER,
    STATUS               VARCHAR(255), -- NEW / PROCESSING / CLOSED / ERROR
    CREATE_DATE          TIMESTAMP(255),
    MODIFY_DATE          TIMESTAMP(255),
    PRIMARY KEY (ID)
);



CREATE INDEX IF NOT EXISTS IDX_SERVICE_CUSTOMER_ID ON SERVICE (CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_COMPONENT_SERVICE_ID ON COMPONENT (SERVICE_ID);
CREATE INDEX IF NOT EXISTS IDX_INVOICE_CUSTOMER_ID ON INVOICE (CUSTOMER_ID);


ALTER TABLE SERVICE
    ADD CONSTRAINT FK_SERVICE_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER (ID)
            ON DELETE CASCADE;

ALTER TABLE COMPONENT
    ADD CONSTRAINT FK_COMPONENT_SERVICE
        FOREIGN KEY (SERVICE_ID)
            REFERENCES SERVICE (ID)
            ON DELETE CASCADE;

ALTER TABLE INVOICE
    ADD CONSTRAINT FK_INVOICE_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
            REFERENCES CUSTOMER (ID)
            ON DELETE CASCADE;


-- Dane testowe dla Next Gen Sales Service
-- 4 klientów, każdy z usługami i 5 komponentami łącznie

-- Dodaj klientów
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, EMAIL, PESEL, TYPE, STATUS, CREATE_DATE, MODIFY_DATE)
VALUES ('Jan', 'Kowalski', 'jan.kowalski@example.com', '85010112345', 'INDIVIDUAL', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Anna', 'Nowak', 'anna.nowak@example.com', '90020298765', 'INDIVIDUAL', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Piotr', 'Wiśniewski', 'piotr.wisniewski@example.com', '78030387654', 'INDIVIDUAL', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       ('Maria', 'Wójcik', 'maria.wojcik@example.com', '92040476543', 'BUSINESS', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

-- Dodaj usługi dla klienta 1 (Jan Kowalski)
INSERT INTO SERVICE (CUSTOMER_ID, TYPE, SERVICE_NAME, SIM, SIM_TYPE, SIM_NUMBER, STATUS, CREATE_DATE, MODIFY_DATE)
VALUES (1, 'MOBILE', '48501234567', 'SIM-001', 'SIM', '8948012345678901234', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (1, 'INTERNET', 'Internet domowy', NULL, NULL, NULL, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj komponenty dla klienta 1 (5 komponentów łącznie)
INSERT INTO COMPONENT (SERVICE_ID, NAME, EXPIRY_DATE, TYPE, PARAMETER_NAME, PARAMETER_VALUE, STATUS, CREATE_DATE,
                       MODIFY_DATE)
VALUES (1, 'Nielimitowane rozmowy', '2026-12-31 23:59:59', 'VOICE', 'minuty', 'nielimitowane', 'ACTIVE',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (1, 'Pakiet danych 50GB', '2026-12-31 23:59:59', 'DATA', 'limit_danych', '50GB', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (1, 'Pakiet SMS', '2026-12-31 23:59:59', 'SMS', 'liczba_sms', '1000', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (2, 'Światłowód 500Mbps', '2026-12-31 23:59:59', 'INTERNET', 'predkosc', '500Mbps', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (2, 'Statyczne IP', '2026-12-31 23:59:59', 'INTERNET', 'typ_ip', 'statyczne', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

-- Dodaj usługi dla klienta 2 (Anna Nowak)
INSERT INTO SERVICE (CUSTOMER_ID, TYPE, SERVICE_NAME, SIM, SIM_TYPE, SIM_NUMBER, STATUS, CREATE_DATE, MODIFY_DATE)
VALUES (2, 'MOBILE', '48509876543', 'SIM-002', 'ESIM', '8948098765432109876', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (2, 'TV', 'Telewizja Premium', NULL, NULL, NULL, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj komponenty dla klienta 2 (5 komponentów łącznie)
INSERT INTO COMPONENT (SERVICE_ID, NAME, EXPIRY_DATE, TYPE, PARAMETER_NAME, PARAMETER_VALUE, STATUS, CREATE_DATE,
                       MODIFY_DATE)
VALUES (3, 'Pakiet głosowy 2000min', '2026-06-30 23:59:59', 'VOICE', 'minuty', '2000', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (3, 'Pakiet danych 100GB', '2026-06-30 23:59:59', 'DATA', 'limit_danych', '100GB', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (3, 'Roaming międzynarodowy', '2026-06-30 23:59:59', 'ROAMING', 'strefa', 'UE', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (4, 'Pakiet TV Premium', '2026-12-31 23:59:59', 'TV', 'kanaly', '150', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (4, 'HBO Max', '2026-12-31 23:59:59', 'TV', 'streaming', 'HBO', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj usługi dla klienta 3 (Piotr Wiśniewski)
INSERT INTO SERVICE (CUSTOMER_ID, TYPE, SERVICE_NAME, SIM, SIM_TYPE, SIM_NUMBER, STATUS, CREATE_DATE, MODIFY_DATE)
VALUES (3, 'MOBILE', '48601234567', 'SIM-003', 'SIM', '8948601234567890123', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (3, 'INTERNET', 'Internet biznesowy', NULL, NULL, NULL, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj komponenty dla klienta 3 (5 komponentów łącznie)
INSERT INTO COMPONENT (SERVICE_ID, NAME, EXPIRY_DATE, TYPE, PARAMETER_NAME, PARAMETER_VALUE, STATUS, CREATE_DATE,
                       MODIFY_DATE)
VALUES (5, 'Biznesowy pakiet głosowy nielimitowany', '2027-01-31 23:59:59', 'VOICE', 'minuty', 'nielimitowane',
        'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 'Pakiet danych 200GB', '2027-01-31 23:59:59', 'DATA', 'limit_danych', '200GB', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (5, 'Pakiet SMS Premium', '2027-01-31 23:59:59', 'SMS', 'liczba_sms', '5000', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (6, 'Światłowód 1Gbps', '2027-01-31 23:59:59', 'INTERNET', 'predkosc', '1Gbps', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (6, 'Wsparcie biznesowe 24/7', '2027-01-31 23:59:59', 'SUPPORT', 'poziom', 'premium', 'ACTIVE',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj usługi dla klienta 4 (Maria Wójcik - Biznes)
INSERT INTO SERVICE (CUSTOMER_ID, TYPE, SERVICE_NAME, SIM, SIM_TYPE, SIM_NUMBER, STATUS, CREATE_DATE, MODIFY_DATE)
VALUES (4, 'MOBILE', '48701234567', 'SIM-004', 'ESIM', '8948701234567890123', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (4, 'INTERNET', 'Internet korporacyjny', NULL, NULL, NULL, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj komponenty dla klienta 4 (5 komponentów łącznie)
INSERT INTO COMPONENT (SERVICE_ID, NAME, EXPIRY_DATE, TYPE, PARAMETER_NAME, PARAMETER_VALUE, STATUS, CREATE_DATE,
                       MODIFY_DATE)
VALUES (7, 'Korporacyjny pakiet głosowy', '2027-12-31 23:59:59', 'VOICE', 'minuty', 'nielimitowane', 'ACTIVE',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (7, 'Pakiet danych nielimitowany', '2027-12-31 23:59:59', 'DATA', 'limit_danych', 'nielimitowany', 'ACTIVE',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (7, 'Roaming globalny', '2027-12-31 23:59:59', 'ROAMING', 'strefa', 'SWIATOWY', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP),
       (8, 'Dedykowany światłowód 10Gbps', '2027-12-31 23:59:59', 'INTERNET', 'predkosc', '10Gbps', 'ACTIVE',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (8, 'Usługa VPN', '2027-12-31 23:59:59', 'SECURITY', 'tunele_vpn', '10', 'ACTIVE', CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);

-- Dodaj faktury dla wszystkich klientów
INSERT INTO INVOICE (CUSTOMER_ID, BILLING_PERIOD_START_DATE, BILLING_PERIOD_END_DATE, PRICE_GROSS, STATUS, CREATE_DATE,
                     MODIFY_DATE)
VALUES (1, '2025-09-01 00:00:00', '2025-09-30 23:59:59', '149.99', 'PAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (1, '2025-10-01 00:00:00', '2025-10-31 23:59:59', '149.99', 'UNPAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, '2025-09-01 00:00:00', '2025-09-30 23:59:59', '199.99', 'PAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, '2025-10-01 00:00:00', '2025-10-31 23:59:59', '199.99', 'UNPAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, '2025-09-01 00:00:00', '2025-09-30 23:59:59', '299.99', 'PAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, '2025-10-01 00:00:00', '2025-10-31 23:59:59', '299.99', 'PAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (4, '2025-09-01 00:00:00', '2025-09-30 23:59:59', '899.99', 'PAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (4, '2025-10-01 00:00:00', '2025-10-31 23:59:59', '899.99', 'UNPAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Dodaj przykładowe komponenty do katalogu
INSERT INTO COMPONENT_CATALOG (TYPE, PRICE_MIN, PRICE_MAX, PARAMETER_NAME, PARAMETER_VALUE, STATUS, CREATE_DATE,
                               MODIFY_DATE)
VALUES ('MOBILE', '39.99', '49.99', 'limit_danych', '50GB', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('MOBILE', '69.99', '79.99', 'limit_danych', '100GB', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('MOBILE', '89.99', '99.99', 'limit_danych', 'nielimitowany', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('INTERNET', '49.99', '59.99', 'predkosc', '300Mbps', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('INTERNET', '69.99', '79.99', 'predkosc', '600Mbps', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('INTERNET', '89.99', '99.99', 'predkosc', '1Gbps', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('TV', '29.99', '39.99', 'kanaly', '100', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('TV', '49.99', '59.99', 'kanaly', '150', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
